website/__init__.py
from flask import Flask;

def create_app():
    app = Flask(__name__)
    
    from .views import views
    
    app.register_blueprint(views, url_prefix='/')
    return app

website/views.py
from flask import Blueprint, send_file, render_template,flash, request, redirect, json,session, Response
from flask_session import Session
import cv2
from datetime import datetime

import numpy as np

views = Blueprint('views', __name__)

camera = cv2.VideoCapture(0)
model = 'website/data/best.onnx'
text  = "website/data/kanker_text.txt"
net = cv2.dnn.readNetFromONNX(model)
file = open(text, "r")
classess = file.read().split('\n')# generate frame by frame from camera


def camera_frames():
    while True:
        # Capture frame-by-frame
        success, frame = camera.read()  # read the camera frame
        if not success:
            break
        else:
            frame = cv2.resize(frame, (1000, 600))
            blob = cv2.dnn.blobFromImage(frame, scalefactor=1.0 / 255, size=(640, 640), mean=[0, 0, 0], swapRB=True, crop=False)
            net.setInput(blob)
            detections = net.forward()[0]
            classes_ids = []
            confidences = []
            boxes = []
            rows = detections.shape[0]

            img_width, img_height = frame.shape[1], frame.shape[0]
            x_scale = img_width/640
            y_scale = img_height/640

            for i in range(rows):
                row = detections[i]
                confidence = row[4]
                if confidence > 0.5:
                    classes_score = row[5:]
                    ind = np.argmax(classes_score)
                    if classes_score[ind] > 0.5:
                        classes_ids.append(ind)
                        confidences.append(confidence)
                        cx, cy, w, h = row[:4]
                        x1 = int((cx - w / 2) * x_scale)
                        y1 = int((cy - h / 2) * y_scale)
                        width = int(w * x_scale)
                        height = int(h * y_scale)
                        box = np.array([x1, y1, width, height])
                        boxes.append(box)
            indices = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.5)
            for i in indices:
                x1, y1, w, h = boxes[i]
                label = classess[classes_ids[i]]
                conf = confidences[i]
                text = label
                cv2.rectangle(frame, (x1, y1), (x1 + w, y1 + h), (255, 0, 0), 2)
                cv2.putText(frame, text, (x1, y1 - 2), cv2.FONT_HERSHEY_COMPLEX, 0.7, (255, 0, 255), 2)
            if type(indices) is not tuple:
                cv2.imwrite('website/static/hasil_foto_scan.jpg', frame)

            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()
            yield (b'--frame\r\n'
                b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

@views.route('/ambil-foto')
def ambilFoto():
    return send_file('static/foto.jpg', as_attachment=True)

@views.route('/video')
def video():
    #Video streaming route. Put this in the src attribute of an img tag
    return Response(camera_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')

@views.route('/')
def home():
    return render_template('index.html', ttl='Deteksi Kanker Melanoma')

@views.route('/detect')
def detect():
    return render_template('camera_detection.html', ttl='Deteksi Kanker Melanoma')
@views.route('/information')
def info():
    return render_template('information.html', ttl='Deteksi Kanker Melanoma')

@views.route('/superficial-melanoma')
def superficialMelanoma():
    return render_template('superficial-melanoma.html', ttl='Superficial Melanoma')

@views.route('/nodular-melanoma')
def nodularMelanoma():
    return render_template('nodular-melanoma.html', ttl='Nodular Melanoma')

@views.route('/lentigo-melanoma')
def lentigoMelanoma():
    return render_template('lentigo-melanoma.html', ttl='Lentigo Maligna Melanoma')

@views.route('/acral-melanoma')
def acralMelanoma():
    return render_template('acral-melanoma.html', ttl='Acral Lentiginous Melanoma')

@views.route('/faktor-terkena-melanoma')
def faktorMelanoma():
    return render_template('faktor-melanoma.html', ttl='Faktor yang Dapat Menyebabkan Terkena Kanker Melanoma')

website/templates/acral-melanoma.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="/information" class="nav-link " id="home"><b><i style="color: whitesmoke;margin-left:15px" class="fa-solid fa-arrow-left"></i></b></a>
        </li>
    </ul>
</nav>
<br>
<div class="row ms-4 me-4 mt-1">
    <div class="col-sm-12 mb-3 mb-sm-0">
        <h3><strong>Acral Lentiginous Melanoma</strong></h3>
        <br>
        <div class="card">
            <div class="card-body">
                <center>
                    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="{{url_for('static', filename='acral1.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='acral2.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='acral3.jpg')}}" alt="">
                          </div>
                        </div>
                      </div>
                </center>
                <br>
                <p style="text-align: justify;">
                    &nbsp Acral Lentiginous Melanoma (ALM) merupakan jenis kanker kulit yang jarang terjadi dan bentuk kelainan dapat berbeda sesuai dengan lokasi melanoma, biasanya pada telapak tangan, kaki, hingga kuku (Goydos & Shoen, 2016). ALM hanya 2% hingga 8% dari melanoma pada orang kulit putih tetapi merupakan bentuk yang paling umum pada individu berpigmen gelap (60%-72% pada Afrika Amerika dan 29% hingga 46% pada orang Asia). ALM lebih sering terdiagnosis pada populasi yang lebih tua, dengan usia rata-rata onset 65 tahun dan paling umum terjadi pada bagian telapak kaki, yang diikuti dengan telapak tangan dan subungual (bagian bawah kuku). ALM tidak dianggap terkait dengan paparan sinar matahari. Karakteristik melanoma lentiginosa akral meliputi:
                </p>
                <ol type="a" class="ms-2">
                    <li>Ukuran besar: >6 mm dan seringkali berdiameter beberapa sentimeter atau lebih saat didiagnosis.</li>
                    <li>Pigmentasi variabel: paling sering campuran warna coklat, dan biru-abu-abu, hitam dan merah.</li>
                    <li>Permukaan halus pada awalnya, kemudian menjadi lebih tebal dengan permukaan tidak beraturan yang mungkin kering atau berkutil.</li>
                    <li>Ulserasi atau perdarahan.</li>
                </ol>
                <p style="text-align: justify;">
                    &nbsp Varian ALM subungual atau bawah kuku biasanya terjadi pada ibu jari atau jempol kaki, memiliki karakteristik, yaitu :
                </p>
                <ol type="a" class="ms-2">
                    <li>Tampak sebagai perubahan warna coklat menjadi hitam atau pertumbuhan pada bantalan kuku.</li>
                    <li>Garis kuku longitudinal yang melebar, gelap, atau berpigmen tidak teratur (melanonychia striata) dengan atau tanpa distrofi kuku dan elevasi lempeng kuku dapat terlihat.</li>
                    <li>Tanda Hutchinson, ditemukannya pigmentasi pada lipatan kuku bagian proksimal, dapat ditemukan dengan melanoma subungual.</li>
                </ol>
            </div>
        </div>
    </div>
</div>

{%endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" crossorigin="anonymous">
    <style>
        #cari {
            animation: fadeInAnimation ease-out 2s;
            animation-iteration-count: 1;
            animation-fill-mode: forwards;
        }
        @keyframes fadeInAnimation {
            0% {
                opacity: 0;
            }
            100% {
                opacity: 1;
             }
        }
        .accordion-button::after {
            background-image: initial;
          }
          
          .accordion-button:not(.collapsed)::after {
            background-image: initial;
          }
    </style>
</head>
<body>
    
    {% block content %}

    {%endblock%}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script type="text/javascript">
        var btn = document.getElementById('btn')
        var cari = document.getElementById('cari')
        btn.onclick = function(){
            cari.style.display = 'block'
            btn.style.display = 'none'
        }
    </script>
</body>
</html>

website/templates/camera_detection.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}

<center>
    <div style="height:60px;padding-top: 15px;background-color: dodgerblue;color: white;">
        <h3><b>Indikasi Resiko</b></h3>
    </div>
    <div style="width: 100%;padding-left:3px;padding-right:3px;padding-top:3px">
        <img src="{{ url_for('views.video') }}"  class="card-img-top" alt="...">
    </div>
</center>
<div class="row">
    <center>
        <table style="width: 95%;margin-top: 190px; position:fixed;">
            <tr>
                <td>
                    <center>
                        <a href="/ambil-foto">
                            <button style="width: 245px; padding-top: 10px; padding-bottom: 10px;padding-left:8px" class="btn btn-primary btn-md"><b>Ambil Gambar</b></button>
                        </a>
                        </center>
                </td>
                <td>
                    <center>
                        <a href="/">
                            <button style="width: 245px; padding-top: 10px; padding-bottom: 10px;" class="btn btn-primary btn-md"><b>Kembali</b></button>
                        </a>
                    </center>
                </td>
            </tr>
        </table>
    </center>
</div>
{%endblock%}

website/templates/faktor-melanoma.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="/information" class="nav-link " id="home"><b><i style="color: whitesmoke;margin-left:15px" class="fa-solid fa-arrow-left"></i></b></a>
        </li>
    </ul>
</nav>
<br>
<div class="row ms-4 me-4 mt-1">
    <div class="col-sm-12 mb-3 mb-sm-0">
        <h3><strong>Faktor yang Dapat Menyebabkan Terkena Kanker Melanoma</strong></h3>
        <br>
        <div class="card">
            <div class="card-body">
                <br>
                <p style="text-align: justify;">
                    &nbsp Ada beberapa faktor yang dapat menyebabkan seseorang terkena kanker melanoma yaitu:
                </p>
                <ol type="a" class="ms-2">
                    <li>Riwayat sengatan matahari dan/atau paparan sinar matahari yang berlebihan. Sinar UV bisa berasal dari matahari atau saat sedang melakukan proses tanning dengan tanning beds.</li>
                    <li>Melanocytic Nevus, atau salah satu dari tumor berpigmen yang jinak. Biasanya mulai terlihat hanya pada anak-anak dan remaja. Nevus Melanotik ini sebenarnya tidak berbahaya, tetapi jika jumlahnya banyak hingga >100 nevi tipikal dan bentuk tidak beraturan, memiliki kemungkinan melanoma.</li>
                    <li>Memiliki mata biru atau hijau, rambut pirang atau merah, warna kulit cerah.</li>
                    <li>Riwayat keluarga menderita melanoma.</li>
                    <li>Pernah menderita melanoma sebelumnya.</li>
                    <li>Immosupresi:sistem imun dalam keadaan lemah atau sedang mendapat terapi obat yang menekan sistem imun.</li>
                    <li>Usia rata-rata diagnosis adalah 63 tahun, dengan 15% kurang dari 45 tahun%.</li>
                    <li>Mutasi p16.</li>
                    <li>Genetik (mutasi gen CDKN2a, CDK4, POT1 dan TERT).</li>
                </ol>
                <p style="text-align: justify;">
                    &nbsp Varian ALM subungual atau bawah kuku biasanya terjadi pada ibu jari atau jempol kaki, memiliki karakteristik, yaitu :
                </p>
                <ol type="a" class="ms-2">
                    <li>Tampak sebagai perubahan warna coklat menjadi hitam atau pertumbuhan pada bantalan kuku.</li>
                    <li>Garis kuku longitudinal yang melebar, gelap, atau berpigmen tidak teratur (melanonychia striata) dengan atau tanpa distrofi kuku dan elevasi lempeng kuku dapat terlihat.</li>
                    <li>Tanda Hutchinson, ditemukannya pigmentasi pada lipatan kuku bagian proksimal, dapat ditemukan dengan melanoma subungual.</li>
                </ol>
            </div>
        </div>
    </div>
</div>

{%endblock%}

website/templates/index.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}

<div class="container-fluid py-3">
    <center>
        <h3>
            <img src="{{url_for('static', filename='File.png')}}" style="width: 60px;"/> <b>Deteksi Kanker</b>
        </h3>
    </center>
    <br><br>
    
    <center>
        <table style="margin-top: 190px;">
            <tr>
                <td>
                    <center>
                        <a href="/detect" style="margin-right:10px">
                            <button style="width: 230px; padding-top: 10px; padding-bottom: 32px;padding-left:8px" class="btn btn-primary btn-md">
                                <b>SCAN</b><br>
                                <p>Mulai Scan Kulitmu</p>
                            </button>
                        </a>
                    </center>
                </td>
                <td>
                    <center>
                        <a href="/information" style="margin-left:10px">
                            <button style="width: 230px; padding-top: 10px; padding-bottom: 10px;" class="btn btn-primary btn-md">
                                <b>INFORMASI</b><br>
                                <p>Cari Informasi Tentang <br> Kanker</p>
                            </button>
                        </a>
                    </center>
                </td>
            </tr>
        </table>
    </center>
</div>


{%endblock%}

website/templates/information.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="/" class="nav-link " id="home"><b><i style="color: whitesmoke;margin-left:15px" class="fa-solid fa-arrow-left"></i></b></a>
        </li>
    </ul>
</nav>
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" style="background-color: white;color:black" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <b>
                    Tipe Kanker Kulit
                </b>
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                
                <div class="list-group list-group-flush">
                    <a href="/superficial-melanoma" class="list-group-item list-group-item-action">Superficial Spreading Melanoma</a>
                    <a href="/nodular-melanoma" class="list-group-item list-group-item-action">Nodular Melanoma</a>
                    <a href="/lentigo-melanoma" class="list-group-item list-group-item-action">Lentigo Melanoma</a>
                    <a href="/acral-melanoma" class="list-group-item list-group-item-action">Acral Lentiginous Melanoma</a>
                </div>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
            <a href="/faktor-terkena-melanoma" style="text-decoration: none">
                <button class="accordion-button" type="button" style="background-color: white;color:black">
                    <b>
                        Faktor yang Dapat Menyebabkan Terkena Kanker Melanoma
                    </b>
                </button>
            </a>
        </h2>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button" type="button" style="background-color: white;color:black" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                <b>
                    Salah Satu Cara Mengetahui Kanker Melanoma dengan Tahi Lalat Biasa
                </b>
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                    <div class="list-group list-group-flush">
                        <button type="button" class="list-group-item list-group-item-action" aria-current="true">
                            <b> Asymmetry (Asimetri)</b> <br> &nbsp Tahi lalat memiliki bentuk asimetri sedangkan melanoma tidak.
                        </button>
                        <button type="button" class="list-group-item list-group-item-action">
                            <b> Border (Tepi)</b> <br> &nbsp Tahi lalat memiliki tepi beraturan sedangkan memiliki tepi yang tidak beraturan..
                        </button>
                        <button type="button" class="list-group-item list-group-item-action">
                            <b> Color (Warna)</b> <br> &nbsp Tahi lalat berwarna hitam sedangkan melanoma memiliki warna yang beragam.
                        </button>
                        <button type="button" class="list-group-item list-group-item-action">
                            <b> Diameter (Diameter)</b> <br> &nbsp Diameter tahi lalat yang lebih besar dari ukuran kacang polong ( >5mm ).
                        </button>
                        <button type="button" class="list-group-item list-group-item-action">
                            <b> Evolution (Evolusi)</b> <br> &nbsp Jika tahi lalat biasa mengalami perubahan bentuk maka bisa menjurus pada melanoma.
                        </button>
                    </div>
            </div>
        </div>
    </div>
</div>


{%endblock%}

website/templates/lentigo-melanoma.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="/information" class="nav-link " id="home"><b><i style="color: whitesmoke;margin-left:15px" class="fa-solid fa-arrow-left"></i></b></a>
        </li>
    </ul>
</nav>
<br>
<div class="row ms-4 me-4 mt-1">
    <div class="col-sm-12 mb-3 mb-sm-0">
        <h3><strong>Lentigo Maligna Melanoma</strong></h3>
        <br>
        <div class="card">
            <div class="card-body">
                <center>
                    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="{{url_for('static', filename='lentigo1.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='lentigo2.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='lentigo3.jpg')}}" alt="">
                          </div>
                        </div>
                      </div>
                </center>
                <br>
                <p style="text-align: justify;">
                    &nbsp Lentigo maligna adalah melanoma in situ (melanoma tingkat 0) dengan fase pertumbuhan yang Panjang yang akhirnya menjadi invasif dan disebut sebagai Lentigo Maligna Melanoma (LMM). Tingkat keseringterjadian LMM adalah 10-15% seluruh melanoma kulit. Bagian yang paling sering adalah di wajah yang terpapar sinar matahari secara kronis, di pipi dan hidung khususnya; leher, kulit kepala, dan telinga pada pria. Penampilan klinis pada awal adalah makula awalnya datar, yang secara perlahan membesar, berwarna cokelat, seperti bintik-bintik (n) dengan bentuk tidak teratur dan corak cokelat dan kecokelatan yang bervariasi, biasanya timbul dengan latar belakang kerusakan karena paparan sinar matahari. Sering kali kedua LM dan LMM memiliki batas yang tidak jelas secara klinis, yang mungkin dikaburkan oleh latar belakang kerusakan aktinik yang terdiri dari lentigo, keratosis aktinik berpigmen, atau ephelida kelainan berupa bentuk yang berbatas tegas, berwarna coklat kehitaman serta tidak homogen, bentuk tidak teratur, dan pada bagian tertentu dapat tumbuh nodul yang berbatas tegas setelah bertahun-tahun. LM dan LMM dikaitkan dengan tingkat pertumbuhan lateral subklinis yang luas secara signifikan lebih tinggi, menghasilkan tingkat kekambuhan yang lebih tinggi dengan margin standar yang direkomendasikan dan kegagalan untuk memotong lesi sepenuhnya dan memiliki hubungan yang paling tidak umum dengan nevi, pada 3% kasus.
                </p>
            </div>
        </div>
    </div>
</div>

{%endblock%}

website/templates/nodular-melanoma.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="/information" class="nav-link " id="home"><b><i style="color: whitesmoke;margin-left:15px" class="fa-solid fa-arrow-left"></i></b></a>
        </li>
    </ul>
</nav>
<br>
<div class="row ms-4 me-4 mt-1">
    <div class="col-sm-12 mb-3 mb-sm-0">
        <h3><strong>Nodular Melanoma</strong></h3>
        <br>
        <div class="card">
            <div class="card-body">
                <center>
                    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="{{url_for('static', filename='nodular1.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='nodular1.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='nodular1.jpg')}}" alt="">
                          </div>
                        </div>
                      </div>
                </center>
                <br>
                <p style="text-align: justify;">
                    &nbsp Nodular Melanoma (NM) merupakan subtipe melanoma yang paling sering terjadi kedua setelah SMM, sekitar 15% hingga 30% dari semua melanoma. NM memiliki beberapa ciri khas, yaitu :
                </p>
                <ol type="a" class="ms-2">
                    <li>NM luar biasa berevolusi dengan cepat, sering kali muncul dalam beberapa minggu hingga bulan.</li>
                    <li>Lokasi paling sering muncul pada batang tubuh.</li>
                    <li>lebih sering tidak memiliki fase pertumbuhan radial yang jelas.</li>
                    <li>NM lebih sering terjadi de novo (mutasi germline baru yang tidak diwarisi dari kedua orang tua) daripada muncul pada nevus yang sudah ada sebelumnya.</li>
                    <li>NM biasanya muncul sebagai lesi timbul biru tua-kehitaman atau merah kebiruan yang seragam, tetapi 5% di antaranya amelanotik.</li>
                </ol>
                <p style="text-align: justify;">
                    Lesi awal nodular melanoma seringkali kurang asimetri, memiliki batas teratur, dan warna seragam. NM yang berpigmen memiliki ciri berupa nodul berwarna biru kehitaman dengan batas tegas serta mempunyai variasi bentuk yaitu bentuk dengan permukaan licin pada lapisan epidermis, nodus yang menonjol dengan bentuk tidak teratur pada permukaan kulit, dan bentuk eksofitik dengan ulserasi. SSM dan NM memiliki tingkat mutasi tertinggi pada gen BRAF, hingga 56% dari melanoma mempunyai perubahan ini.
                </p>
            </div>
        </div>
    </div>
</div>

{%endblock%}

website/templates/superficial-melanoma.html
{% extends "base.html" %} 
{% block title %}{{ ttl }} {% endblock %} 
{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a href="/information" class="nav-link " id="home"><b><i style="color: whitesmoke;margin-left:15px" class="fa-solid fa-arrow-left"></i></b></a>
        </li>
    </ul>
</nav>
<br>
<div class="row ms-4 me-4 mt-1">
    <div class="col-sm-12 mb-3 mb-sm-0">
        <h3><strong>Superficial Melanoma</strong></h3>
        <br>
        <div class="card">
            <div class="card-body">
                <center>
                    <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                            <img src="{{url_for('static', filename='superficial1.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='superficial2.jpg')}}" alt="">
                          </div>
                          <div class="carousel-item">
                            <img src="{{url_for('static', filename='superficial3.jpg')}}" alt="">
                          </div>
                        </div>
                      </div>
                </center>
                <br>
                <p style="text-align: justify;">
                    &nbsp Superficial Spreading Melanoma (SMM) merupakan kelainan yang sering terjadi pada orang berkulit putih yaitu sekitar 70% dari semua melanoma kulit. Kelainan berupa bercak dengan ukuran beberapa milimeter sampai beberapa cm dengan warna bervariasi (waxy, kehitaman, kecoklatan, putih, biru), tidak teratur, berbatas tegas tetapi tidak halus atau irregular dengan sedikit penonjolan di permukaan kulit. Dengan menggunakan aturan ABCDE, melanoma jenis ini memiliki gambaran klinis paling klasik yaitu batas tidak teratur dan pigmentasi tidak teratur, tetapi mungkin muncul secara halus sebagai area fokus diskret hiperpigmentasi dalam nevus yang sudah ada sebelumnya. Nevus adalah bercak warna pada permukaan kulit, contohnya adalah tahi lalat. SMM adalah subtipe melanoma yang sering dikaitkan dengan nevi yang sudah ada, bisa jadi nevi perlahan-lahan berubah selama berbulan-bulan hingga bertahun-tahun, kondisi ini dapat menunjukkan ada yang salah jika terjadi pada nevus atipikal.
                </p>
            </div>
        </div>
    </div>
</div>

{%endblock%}